<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\IndexView
 */
class IndexViewTest extends TestCase
{
    /**
     * @test
     */
    public function change_log_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('v2/changelog');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('v2');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function options_change_log_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('v2/changelog');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function options_index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('v2');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
